// console.log(getCurrencyCode("1 FRANC ELVETIAN"))  
// console.log(getCurrencyCode("1 DOLAR CANADA"))  
// console.log(getCurrencyCode("1 Lira sterlina"))  
// console.log(getCurrencyCode("1 DOLAR AUSTRALIAN"))  
// console.log(getCurrencyCode("1 COROANA NORVEGIA"))  
// console.log(getCurrencyCode("1 COROANA DANEZA"))  
// console.log(getCurrencyCode("1 COROANA SUEDEZA"))  
// console.log(getCurrencyCode("1 YEN JAPONEZ"))  
// console.log(getCurrencyCode("1 FORINT UNGARIA"))  
// console.log(getCurrencyCode("1 ZLOT POLONIA"))  
// console.log(getCurrencyCode("1 COROANA CEHIA"))  
// console.log(getCurrencyCode("1 RUBLA RUSEASCA"))  
// console.log(getCurrencyCode("1 LEVA BULGARIA")) 
// 
// console.log(getCurencyMultiplier("100 Yeni japonezi"))